# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import connector_pb2 as connector__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in connector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConnectorServiceStub(object):
    """ConnectorService permite túnel reverso: Connector inicia conexión, Gateway envía comandos
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/connector.ConnectorService/Connect',
                request_serializer=connector__pb2.ConnectorMessage.SerializeToString,
                response_deserializer=connector__pb2.GatewayCommand.FromString,
                _registered_method=True)


class ConnectorServiceServicer(object):
    """ConnectorService permite túnel reverso: Connector inicia conexión, Gateway envía comandos
    """

    def Connect(self, request_iterator, context):
        """Connect establece stream bidireccional para el túnel reverso
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=connector__pb2.ConnectorMessage.FromString,
                    response_serializer=connector__pb2.GatewayCommand.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'connector.ConnectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('connector.ConnectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConnectorService(object):
    """ConnectorService permite túnel reverso: Connector inicia conexión, Gateway envía comandos
    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/connector.ConnectorService/Connect',
            connector__pb2.ConnectorMessage.SerializeToString,
            connector__pb2.GatewayCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
